version: '3'

services:

  control-server:
    image: alinchis/docker-control-server
    volumes:
      - ~/Git/control-server:/root/Git/control-server
    working_dir: /root/Git/control-server
    command: npm start
    depends_on:
      - "sql-server"
    ports:
      - "3030:3030"

  display-server:
    image: alinchis/docker-display-server
    volumes:
      - ~/Git/display-server:/root/Git/display-server
    working_dir: /root/Git/display-server
    command: npm run dev
    ports:
      - "8888:8888"
    depends_on:
      - "control-server"

  sql-server:
    image: alinchis/docker-sql-server
    volumes:
      - ~/Git/docker-data/PostgreSQL/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
